apiVersion: v1
kind: Pod
metadata:
  name: jenkins-with-emptydir-volume
spec:
  
  containers:
    - name: jenkins-container
      image: jenkins/jenkins:lts
      ports:
      - containerPort: 8080
      volumeMounts:
      - mountPath: /cache
        name: cache-volume

  volumes:
  - name: cache-volume
    emptyDir: {}
  