apiVersion: v1
kind: Pod
metadata:
  name: nginx-using-hostpath-volume
  labels:
    app: nginx
    tier: dev
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
      - mountPath: /test-pd
        name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory