apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jenkins-ds
spec:
  #pod template
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080

  #pod selector
  selector:
    matchLabels:
     name: jenkins