apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"  #added
      readOnly: true  #added

  volumes:
  - name: foo
    secret:  #added
      secretName: opaque-secret #keys in secrets are stored as files in mount path inside containers